services:
  postgres:
    image: postgres:16
    container_name: battery_postgres
    environment:
      POSTGRES_USER: battery_user
      POSTGRES_PASSWORD: battery_pass
      POSTGRES_DB: battery_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  grafana:
    image: grafana/grafana-oss:latest
    container_name: battery_grafana
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    volumes:
      - grafana_data:/var/lib/grafana

  app:
    build: .
    container_name: battery_app
    depends_on:
      - postgres
    volumes:
      - .:/app
    environment:
      DB_USER: battery_user
      DB_PASSWORD: battery_pass
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: battery_db


  jenkins:
    build:
      context: .
      dockerfile: docker/jenkins/Dockerfile
    container_name: battery_jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkins_home

volumes:
  postgres_data:
  grafana_data:
  jenkins_data: